Import pre implementation
tiko-star/transporter pull request #1
Opened 2022-02-28 12:22 UTC by k3rnel

2022-03-16 07:14 UTC, tiko-star requested changes

2022-03-18 08:38 UTC, tiko-star requested changes

2022-03-18 08:38 UTC, tiko-star commented on app.js
> +// After consuming start export of the document.
Likel es u toxel nuyn dzev

2022-03-18 08:38 UTC, tiko-star commented on config.js
> +    ROOT_PATH
storaket dir misht verjum

2022-03-18 08:38 UTC, tiko-star commented on handlers/onExportConsumed.js
> + * Return event handler for emitted "exportConsumed" events.
eventi anuny consumed:export a

2022-03-18 08:38 UTC, tiko-star commented on handlers/onExported.js
> +module.exports = (compressionType) => {
es mi jnji

2022-03-18 08:38 UTC, tiko-star commented on handlers/onImportConsumed.js
> +module.exports = (emitter, connectionInstance) => {
ste normal function gri eli, es unnamednery menak runtimer hamar anenq

2022-03-18 08:38 UTC, tiko-star commented on handlers/onImportConsumed.js
> + * Return event handler for emitted "importConsumed" events.
es anunnel chisht gri eventi

2022-03-18 08:38 UTC, tiko-star commented on handlers/onImported.js
> +module.exports = (compressionType) => {
stexel normal function gri

2022-03-18 08:38 UTC, tiko-star commented on errors/InvalidEntityTypeError.js
>  "use strict";
es file service mej Error folder sarqi ytex pahi, ira levely service levela

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentCreator/ColumnResolver/index.js
> +const InvalidEntityTypeError = require("../../../errors/InvalidEntityTypeError.js");
stexel Error - i mejic use kanes

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentCreator/Exporter.js
> +     * @param format
es sranc typernel nshi

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/DocumentImporter.js
> +const { join } = require("path");
ete usadir es exel es desturctov importnery nerqevum em grum sovoraknnery verevum

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/DocumentImporter.js
> +    constructor(connection) {
stex comment dir

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/DocumentImporter.js
> +        const importer = Factory.createImporter(type, this.connection, queryResolver, resultReporter);
```js
const importer = Factory.createImporter(type, this.connection, queryResolver, new ResultReporter());
```
xi chenq senc anum?

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/DocumentImporter.js
> +
comment

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/DocumentImporter.js
> +
comment

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/DocumentImporter.js
> +
comment

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/Driver/AbstractDriver.js
> +     * @returns {Promise<Array>}
es type sxala

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/Driver/CategoryImporterDriver.js
> +
Poxos voch mi comment ches grel

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/Driver/CategoryImporterDriver.js
> +        return this.resultReporter;
es side effecta?

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/Driver/CategoryImporterDriver.js
> +            mapping,
stex itogum mapingy arandzin es hashvum?

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/QueryResolver/Resolvers/CategoryQueryResolver.js
> +     * Updates given category parentId by category id.
Update

2022-03-18 08:38 UTC, tiko-star commented on service/DocumentImporter/QueryResolver/Resolvers/CategoryQueryResolver.js
> +    updateCategory({newParentId = null, id = null}) {
updateCategoryParentId, mekel xi en null by default? ete null ekan havaqi ban darnum

2022-03-18 08:38 UTC, tiko-star commented on utils/Stack/index.js
> +module.exports = class {
normal class sarqi anunov

2022-03-18 08:38 UTC, tiko-star commented on utils/Stack/index.js
> +		this.items = [
qo mot itemsy arraya xies wrap anum arrayov?

2022-03-18 08:38 UTC, tiko-star commented on utils/Stack/index.js
> +
es fileid formattingy sxala

2022-03-18 10:25 UTC, k3rnel commented on service/DocumentImporter/Driver/CategoryImporterDriver.js
> +            mapping,
ha, MappingApplier ka, iran talis es worksheetRow u mapping inqy xpuma irar u veradardznuma maqur row vorov karas ashxates

2022-03-18 10:29 UTC, k3rnel commented on service/DocumentImporter/QueryResolver/Resolvers/CategoryQueryResolver.js
> +    updateCategory({newParentId = null, id = null}) {
esi toxel em updateCategory vortev es pahin parentina update anum, bayc heto status karoxa avelana, vor rename chanem methody. Commentum grel em es pahin incha anum es methody, heto kpoxem commenty erb vor avelacnenq status kam urish data

2022-03-21 10:02 UTC, tiko-star commented on app.js
> +// After consuming start the export of the document.
After consuming start the import of the document.

2022-03-21 10:05 UTC, tiko-star commented on service/DocumentCreator/Driver/AbstractDriver.js
> +     * @param {Object} type Exportable entity type.
es String chi?

2022-03-21 10:07 UTC, tiko-star commented on service/DocumentCreator/Exporter.js
> +     * @param {object} type for exporting.
es masery ber hin dzevin

2022-03-21 10:34 UTC, tiko-star approved these changes

2022-03-21 10:34 UTC, merged